### ISSUE TITLE
Add TorchIO to open-source tools

### ISSUE THREAD

**Issue by fepegar** [JunMa11/SOTA-MedSeg#2]
Would you please consider adding [TorchIO](https://github.com/fepegar/torchio) to the [list of open-source tools](https://github.com/JunMa11/SOTA-MedSeg#awesome-open-source-tools)?

**Comment by JunMa11** [comment]
Hi @fepegar ,

Thanks for sharing the great tool.
I have added it.

**Comment by fepegar** [comment]
Great, thank you very much!
