### ISSUE TITLE
Add MedicalZooPytorch: A pytorch-based deep learning framework for multi-modal 2D/3D medical image segmentation

### ISSUE THREAD

**Issue by black0017** [JunMa11/SOTA-MedSeg#3]
Hello, would you please consider adding MedicalZooPytorch on the open source tools list?
Link: https://github.com/black0017/MedicalZooPytorch

**Comment by JunMa11** [comment]
Awesome! I have added it.

**Comment by black0017** [comment]
You are the best!!!
