### ISSUE TITLE
2018 MICCAI Medical Segmentation Decathlon SOTA结果的一点确认

### ISSUE THREAD

**Issue by chenqz1998** [JunMa11/SOTA-MedSeg#4]
您好，对于2018 MICCAI Medical Segmentation Decathlon的Pancreas & Tumor结果中，Qihang Yu et al. (paper)一文我看到了他们在table3中汇报了80.37/56.36的结果，说否说胰腺癌目前的SOTA分割结果为56.36呢？还是说以table1中汇报的54.41为准？

**Comment by JunMa11** [comment]
Hi @chenqz1998 ,

[Here](https://decathlon-10.grand-challenge.org/evaluation/challenge/leaderboard/) is the SOTA.
