### ISSUE TITLE
ASOCA challenge

### ISSUE THREAD

**Issue by ruiruian** [JunMa11/SOTA-MedSeg#5]
Hi, @JunMa11 

I am very interested in this job，will the excellent methods be open for us to learn? And I have another question to ask,  I have  emailed the signed data confidentiality form for three weeks, but I still do not have permission to download the data, so I want to ask how long did you get the data.

Thank you very much!

**Comment by JunMa11** [comment]
Hi @ruiruian ,

I'm sorry for the late reply. Very busy recently.
Also, thanks for your interest very much.

> will the excellent methods be open for us to learn? 

I do not know, please connect the challenge organizers.


> I want to ask how long did you get the data.

About two weeks.
