### ISSUE TITLE
About Asoca Challenge

### ISSUE THREAD

**Issue by zyx3216825** [JunMa11/SOTA-MedSeg#6]
Hi JunMa11,
        Do you know if can download asoca data at this time，I‘ve sent email and didn't get reply. Could you share your asoca data.Thanks really a lot

**Comment by JunMa11** [comment]
Hi @zyx3216825 ,

I'm sorry that I'm not allowed to share the ASOCA data.

**Comment by zyx3216825** [comment]
sry，did you get asoca reply email from r.gharleghi@student.unsw.edu.au
