### ISSUE TITLE
Question of LiTS 2017 dataset processing and performance report?

### ISSUE THREAD

**Issue by sherjy** [JunMa11/SOTA-MedSeg#7]
Hiiii Jun, thanks for your nice leaderboard collecting repo! 
Here I have a question for  LiTS 2017 dataset performance: https://competitions.codalab.org/competitions/17094#results
I noticed in your paper "How Distance Transform Maps Boost Segmentation CNNs: An Empirical Study" you used this dataset for loss comparison. I'm so confused why the performance could vary so far, just like on leaderboard, the liver tumour segmentation result could be up to 0.7x and the results mentioned in your paper is 0.5x. Thougn there may exist some difference on dataset split and processing.
![image](https://user-images.githubusercontent.com/23369551/127277299-77d90c5d-56ef-428d-a28f-d1ce49e8e155.png)
![image](https://user-images.githubusercontent.com/23369551/127277435-acb71671-d2b3-484f-9a1a-0d873e9b9211.png)

**I really want to use some template dataset processing codes for this dataset to get 0.7x on baselines like V-Net.** Could your give some more guidance? Thanks a lot in advance!

**Comment by JunMa11** [comment]
Hi @sherjy ，

The goal of SegDistMap is to compare different distance map usage rather than pursuing SOTA performance.
So, we only use a very very simple V-Net.

If you opt to obtain better performance, nnU-Net is definitely worth trying!
https://github.com/MIC-DKFZ/nnUNet

Hope the answer helps:)

Best,
Jun

**Comment by sherjy** [comment]
> Hi @sherjy ，
> 
> The goal of SegDistMap is to compare different distance map usage rather than pursuing SOTA performance.
> So, we only use a very very simple V-Net.
> 
> If you opt to obtain better performance, nnU-Net is definitely worth trying!
> https://github.com/MIC-DKFZ/nnUNet
> 
> Hope the answer helps:)
> 
> Best,
> Jun

Thanks a lot for your advice!
